### PR TITLE
Browser build

### PR DESCRIPTION
**Pull request by threepointone**
This is based on mikemintz/rethinkdb-websocket-client

The general idea is to write a polyfill for `net` so that you can create 'servers' and 'sockets' in the browser. I also replaced the `request` module with `superagent`, an isomorphic friendly http client. 

The key file here is TCPPolyfill.js.

We then make a standalone bundle that packages the rethinkdb client, reqlite and the polyfill into one module which is *then* consumed by other modules. 

You can run `npm run browser` in the root dir to generate the browser build `browser.js`. So in a browser context, you'd expect someone to `require('reqlite/browser')` to use it; alternately/also, we could have a `browser` field in `package.json` pointing to `browser.js` (I believe browserify picks that field up automatically)

I also made an `example` folder for experimenting, but we'll wipe this way later. You need to run `npm install` inside the `example` folder, then go back to the root dir and run `webpack --config example/webpack.config.js`, then `open example/index.html` (will make this simpler later, promise)

### CODE REVIEW

**Comment by neumino** [comment]
You need a browser build to build a react component right? So basically what you want is, given a query, execute it locally and immediately provide results while sending a query to the server? What meteor typically calls latency compensation.

If yes, you only need to build a new interface on the server that would rougly be
```

Server.prototype.run = function(queryAst) {
  var query = new Query(this, queryAst, {}, this.token++)
  return query.run()
}
```

Mocking everything including connection seems like a long and painful path. Or maybe I'm missing a use case?

**Comment by threepointone** [comment]
Yes! That would be more convenient. However, the rethinkdb driver right now chooses either XHR or TCP to connect, and doesn't accept a custom 'connection', iirc.

**Comment by neumino** [comment]
There are two solutions for this problem:
- You can send a PR to RethinkDB to duck type the connection
https://github.com/rethinkdb/rethinkdb/blob/next/drivers/javascript/net.coffee#L1454
- You can use the syntax `server.run(query)` where `queryAst` is produced by calling `query.build()` (with the official driver, for `rethinkdbdash`, `query._query` should give you the AST

**Comment by threepointone** [comment]
both sound like good plans. there's already an [issue for the first](https://github.com/rethinkdb/rethinkdb/issues/4316), but maybe I could just override that in runtime. I'll have a crack at the second soon. Thanks!

**Comment by neumino** [comment]
Err I'm sorry @threepointone, the PR slipped through the cracks. Looking into it now.

**Comment by neumino** [comment]
I can't get the browser example to buld
```
michel@xone:~/projects/rethinkdb-all/reqlite$ webpack --config example/webpack.config.js
Hash: 8933b994cbd717c8e1cb
Version: webpack 1.12.6
Time: 459ms
    Asset     Size  Chunks             Chunk Names
bundle.js  1.52 kB       0  [emitted]  example
   [0] multi example 28 bytes {0} [built] [1 error]
    + 1 hidden modules

ERROR in Loader /home/michel/node_modules/babel/index.js?optional[]=runtime didn't return a function
 @ multi example
```

Any hint? I'm looking into it, but maybe you can save me some time :)

**Comment by threepointone** [comment]
Away from a laptop for a couple of hours, will surely see. Try `npm install` to make sure Babel-runtime is available? 

Sorry I haven't gotten to this myself :/ in general, got stuck with some bits that still assume server side, and then got caught up with life :/

**Comment by neumino** [comment]
Went with `browserify`, it makes thing easier :)

**Pull request closed without merging**
