### PR TITLE
Added travis config

### PR DESCRIPTION
**Pull request by zephraph**
This is my first time starting a travis config from scratch, but I think this is all that's needed. 

Specifying _node_ as the version should use the latest stable version of node.

### CODE REVIEW

**Comment by zephraph** [comment]
@neumino, you'll need to follow the [getting started](http://docs.travis-ci.com/user/getting-started/) guide to hook it up.

**Comment by neumino** [comment]
This is a bit more complicated as we need a script to start rethinkdb and reqlite before rolling the test with `npm test`.

**Comment by zephraph** [comment]
Ah, sorry, I forgot about that part. 

Look good now?

**Comment by neumino** [comment]
I think you need to install rethinkdb first right?
https://github.com/travis-ci/travis-ci/issues/2048

I couldn't see that rethinkdb was part of their official stack

**Comment by zephraph** [comment]
D'oh!... Yeah, give me a second.

**Comment by zephraph** [comment]
Installing is a bit of a pain, but regardless, I think that should work.

**Comment by neumino** [comment]
Let's try this

**Comment by zephraph** [comment]
I'm probably about to head to bed, but let me know if you have any success with it.

**Comment by neumino** [comment]
Thanks, it works fine now ;)

**Pull request merged**
