### PR TITLE
replace `__dirname+"/` with `"./`. 

### PR DESCRIPTION
**Pull request by threepointone**
I'm working on making reqlite work in the browser, and this makes it much easier. all the previous passing tests still pass on node.

### CODE REVIEW

**Comment by neumino** [comment]
There's no reason to remove __dirname. If you are working on having reqlite work on the browser, you should just use browserify and add the missing interface (fake connection)

**Comment by threepointone** [comment]
Hi @neumino! I'll gladly remove the changes, (and replace with a plugin that does it at build time). though could I know why you prefer the __dirname format? 

Am working on the fake connection! Will bug you as and when I bump into any walls.

**Comment by neumino** [comment]
`__dirname` is where the file is, `./` is where you execute `node`.

The reason why you actually need something like browserify is that you need to replace `Buffer` with `Int8Array` (and maybe more?)

**Comment by threepointone** [comment]
Pardon? './etc' is relative to the file. 

So far I've had to replace Buffer, net, tls, dgram, etc. it builds! On that note, are you attached to the 'request' module? It's not really built for an 'isomorphic' use case. You could replace it with something lighter like superagent/axios/ or even a fetch shim, and it would easier. Thanks.

**Pull request merged**
