### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by rclai**
`'boolaen' => 'boolean'`

### CODE REVIEW

**Comment by neumino** [comment]
Thanks, can you add a test that will use this code path?

**Comment by neumino** [comment]
Just to be more clear.

If you add a test, because Travis will run them, I can just merge the pull request without having to locally copy, write the test and run it.
I believe that reqlite will keep growing, and the more test the better :)

I'll write more info on how to write a test, but it's pretty simple

```
  it('<function tested> - <num of test>', function(done) {
    var query = <your query>
    compare(query, done);
  });
```
It will run the query against reqlite and rethinkdb and compare the output.

If you generate a random result, you can apply a transformation to the result before comparing the output by providing a function as the third argument of compare.
Something like this:

```
  it('<function tested> - <num of test>', function(done) {
    var query = <your query>
    compare(query, done. function(result) {
      // transform result, for example delete a field.
      return result;
    });
  });
```

**Comment by neumino** [comment]
Merged.
I wrote the tests since there wasn't any guidelines for pull requests before :)

**Comment by rclai** [comment]
Okay, thanks.

**Pull request merged**
